services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      - ./DB/resources/:/docker-entrypoint-initdb.d/
      - data:/var/lib/postgresql/data
    env_file:
      - ./db/.env
    # environment:
    #   POSTGRES_PASSWORD: example123123
    #   DB_USER: my_app_user
    #   DB_PASSWORD: myapppwdasdfawre234234
    #   POSTGRES_DB: appdb2
    #   POSTGRES_USER: administrador
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  # docker compose build 
  backend:
    build:
      context: ./db_controllers
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    env_file:
      - ./db_controllers/.env
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=appdb2
    #   - DB_PASSWORD=myapppwdasdfawre234234
    #   - DB_USER=my_app_user
volumes:
  data: